package com.example.demo.EstadisticasExcel.ReporteGanancias;

public interface PosicionesExcelGananciasParteProductos {
    int FILA_CABECERA_TITULOS = 0;
    int FILA_CABECERA_MEJOR = 1;
    int FILA_CABECERA_PEOR = 6;
    int COLUMNA_CABECERA_RENTABILIDAD = 0;
    int COLUMNA_CABECERA_RENTABILIDAD_3_MESES = 8;
    int COLUMNA_MEJOR_PEOR_HISTORICO = 3;
    int COLUMNA_MEJOR_PEOR_3_MESES = 11;
    int FILA_COMIENZO_DATOS = 2;
    int FILA_COMIENZO_MEJORES_COMIDAS = 1;
    int FILA_COMIENZO_PEORES_COMIDAS = 6;
    int COLUMNA_MEJORES_PEORES_DENOMINACION_HISTORICO = 4;
    int COLUMNA_COMIENZO_DENOMINACION_HISTORICO = 0;
    int COLUMNA_COMIENZO_GANANCIA_HISTORICO = 1;
    int COLUMNA_COMIENZO_DENOMINACION_3_MESES = 8;
    int COLUMNA_COMIENZO_GANANCIA_3_MESES = 9;
    int COLUMNA_MEJORES_PEORES_GANANCIA_HISTORICO = 5;
    int COLUMNA_MEJORES_PEORES_DENOMINACION_3_MESES = 12;
    int COLUMNA_MEJORES_PEORES_GANANCIA_3_MESES = 13;
}
